global:
  # -- Configure the Prometheus operator to use.  Valid values are "coreos", "googleapis", "none"
  promOperator: coreos

# -- Configure the grafana instance that the dashboard will be deploy to
grafanaInstanceLabel: grafana

dashboard:
  enabled: true

podinfo:
  # -- Configure the number of replicas of the target service
  replicaCount: "2"

k6:

  # -- Configure k6 cron schedule
  schedule: "*/6 * * * *"

  # -- Configure k6 cronjob activeDeadlineSeconds
  activeDeadlineSeconds: 600

  # -- Configure k6 container image
  image:
    repository: grafana/k6
    tag: 0.52.0

  # -- Configure k6 resource requests
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

  # -- Configure common labels for k8s resources
  commonLabels: {}

  # -- Configure additional tags for k6 metrics
  tags: {}

  # -- Configure the target(s) of the continuous load
  loadTargetService:
  - method: GET
    url: http://continuous-load-podinfo.continuous-load.svc.cluster.local:9898/status/200
    # -- See https://k6.io/docs/javascript-api/k6-http/params/ for info on accepted parameters
    params:
      tags:
        type: service

  # -- See https://k6.io/docs/using-k6/thresholds/ for info on thresholds for pass/failure.
  thresholds:
    http_req_failed:
    - rate<0.01
    http_req_duration:
    - p(95)<200

  # -- The throughput required
  reqPerSecond: "3"

  # -- Configure k6 datadog address
  statsdAddr: "127.0.0.1:9125"

  additionalAntiAffinity:

  # -- Configure prometheus statsd sidecar
  prometheusStatsd:
    enable: true
    image:
      repository: prom/statsd-exporter
      tag: v0.20.0

    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        memory: 50Mi
