{
 "title": "Continuous Load",
 "description": "Continuous Load Dashboard",
 "time": { "from": "2023-07-18T12:09:50.923Z", "to": "2023-07-18T12:21:05.406Z" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "timespan",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Path Availability (${timespan})",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"service\"}[${timespan}]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"service\"}[${timespan}]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Load Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "K6 - RPS by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(name, status) (rate(k6_http_reqs{\n    namespace=\"continuous-load\"\n}[$__rate_interval])) > 0",
     "legendFormat": "Request {{ name }} - Response  {{ status }}"
    }
   ]
  },
  {
   "title": "K6 - Success Rate (200 responses) - ${timespan}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs{status=\"200\", namespace=\"continuous-load\"}[${timespan}]))/sum(rate(k6_http_reqs{namespace=\"continuous-load\"}[${timespan}])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "K6 - Latency (${timespan})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load\"}[${timespan}]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load\"}[${timespan}]))by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.80, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load\"}[${timespan}]))by (le))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.50, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load\"}[${timespan}]))by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.10, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load\"}[${timespan}]))by (le))",
     "legendFormat": "P10"
    }
   ]
  },
  {
   "title": "Target Podinfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "App - RPS by Path, Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_duration_seconds_count{\n    namespace=\"continuous-load\",\n}[$__rate_interval])) > 0",
     "legendFormat": "Request {{ path }} - Method {{ method }} Response  {{ status }}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"continuous-load\"}[$__rate_interval]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "App - Success Rate (200 responses) - ${timespan}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (path, method)(rate(http_request_duration_seconds_count{status=\"200\", namespace=\"continuous-load\"}[${timespan}]))/sum by (path, method)(rate(http_request_duration_seconds_count{namespace=\"continuous-load\"}[${timespan}])) * 100",
     "legendFormat": "Path: {{path}}, Method: {{ method }}"
    }
   ]
  },
  {
   "title": "App - Latency (${timespan})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load\", path=\"status\"}[${timespan}])) by (le, path, method, status))",
     "legendFormat": "P99 Path: {{path}} Method: {{method}} Status: {{status}}"
    },
    {
     "expr": "histogram_quantile(0.95, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load\", path=\"status\"}[${timespan}])) by (le, path, method, status))",
     "legendFormat": "P95 Path: {{path}} Method: {{method}} Status: {{status}}"
    },
    {
     "expr": "histogram_quantile(0.80, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load\", path=\"status\"}[${timespan}])) by (le, path, method, status))",
     "legendFormat": "P80 Path: {{path}} Method: {{method}} Status: {{status}}"
    },
    {
     "expr": "histogram_quantile(0.50, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load\", path=\"status\"}[${timespan}])) by (le, path, method, status))",
     "legendFormat": "P50 Path: {{path}} Method: {{method}} Status: {{status}}"
    },
    {
     "expr": "histogram_quantile(0.10, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load\", path=\"status\"}[${timespan}])) by (le, path, method, status))",
     "legendFormat": "P10 Path: {{path}} Method: {{method}} Status: {{status}}"
    }
   ]
  }
 ]
}