{
 "title": "Continuous Load",
 "description": "Continuous Load Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "source_namespace", "query": "continuous-load-source" },
   { "name": "target_namespace", "query": "continuous-load-target" },
   { "name": "ingress", "query": "nginx" },
   { "name": "generator", "query": "continuous-load-generator" }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Path Availability (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"service\"}[5m]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"service\"}[5m]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Service Path Availability (1h)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"service\"}[1h]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"service\"}[1h]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Service Path Availability (24h)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"service\"}[24h]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"service\"}[24h]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Service Path Availability (7d)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"service\"}[7d]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"service\"}[7d]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Ingress Path Availability (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"ingress\"}[5m]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"ingress\"}[5m]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Ingress Path Availability (1h)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"ingress\"}[1h]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"ingress\"}[1h]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Ingress Path Availability (24h)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"ingress\"}[24h]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"ingress\"}[24h]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Ingress Path Availability (7d)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    k6_http_reqs{status=\"200\", type=\"ingress\"}[7d]\n  )\n)\n/\nsum by (name) (\n  rate(\n    k6_http_reqs{type=\"ingress\"}[7d]\n  )\n)\n"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "K6RequestName" },
  {
   "title": "Nginx - memory  RSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}",
     "legendFormat": "{{ pod }} - {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}",
     "legendFormat": "{{ pod }} - {{ container }} limit"
    }
   ]
  },
  {
   "title": "Nginx - cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU Total"
    },
    {
     "expr": "irate(container_cpu_user_seconds_total{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU User"
    },
    {
     "expr": "irate(container_cpu_system_seconds_total{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU System"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}",
     "legendFormat": "{{ pod }} - {{ container }} CPU Request"
    }
   ]
  },
  {
   "title": "Nginx - RPS by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(nginx_ingress_controller_requests{\n    exported_namespace=\"$target_namespace\"\n}[$__rate_interval])) > 0",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Nginx - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"200\", exported_namespace=\"$target_namespace\"}[2m]))/sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$target_namespace\"}[2m])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Nginx - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"target-podinfo\", exported_namespace=\"$target_namespace\"}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"target-podinfo\", exported_namespace=\"$target_namespace\"}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"target-podinfo\", exported_namespace=\"$target_namespace\"}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - RPS by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(response_code) (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[$__rate_interval])) > 0",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\", response_code=\"200\"\n}[$__rate_interval])) /sum (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[$__rate_interval])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  { "title": "Load Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "K6 - memory  RSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"continuous-load-generator\", pod=~\"k6-.*\", container=\"k6\"}",
     "legendFormat": "{{ pod }} - {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"continuous-load-generator\", pod=~\"k6-.*\",container=\"k6\"}",
     "legendFormat": "{{ pod }} - {{ container }} limit"
    }
   ]
  },
  {
   "title": "K6 - cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"continuous-load-generator\", pod=~\"k6-.*\", container=\"k6\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU Total"
    },
    {
     "expr": "irate(container_cpu_user_seconds_total{namespace=\"continuous-load-generator\", pod=~\"k6-.*\", container=\"k6\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU User"
    },
    {
     "expr": "irate(container_cpu_system_seconds_total{namespace=\"continuous-load-generator\", pod=~\"k6-.*\", container=\"k6\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU System"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}",
     "legendFormat": "{{ pod }} - {{ container }} CPU Request"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - RPS by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(response_code) (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"k6\", source_workload_namespace=\"continuous-load-generator\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[$__rate_interval])) > 0",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"k6\", source_workload_namespace=\"continuous-load-generator\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\", response_code=\"200\"\n}[$__rate_interval])) /sum (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"k6\", source_workload_namespace=\"continuous-load-generator\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[$__rate_interval])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"source\", source_workload=\"k6\", source_workload_namespace=\"continuous-load-generator\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"source\", source_workload=\"ingress-nginx-controller\", source_workload_namespace=\"nginx\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  {
   "title": "K6 - RPS by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(name, status) (rate(k6_http_reqs{\n    namespace=\"continuous-load-generator\"\n}[$__rate_interval])) > 0",
     "legendFormat": "Request {{ name }} - Response  {{ status }}"
    }
   ]
  },
  {
   "title": "K6 - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs{status=\"200\", namespace=\"continuous-load-generator\"}[2m]))/sum(rate(k6_http_reqs{namespace=\"continuous-load-generator\"}[2m])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "K6 - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load-generator\"}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load-generator\"}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(k6_http_req_duration_bucket{namespace=\"continuous-load-generator\"}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  { "title": "Source Podinfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Source - memory  RSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"continuous-load-source\", pod=~\"source-.*\", container=\"podinfo\"}",
     "legendFormat": "{{ pod }} - {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"continuous-load-source\", pod=~\"source-.*\", container=\"podinfo\"}",
     "legendFormat": "{{ pod }} - {{ container }} limit"
    }
   ]
  },
  {
   "title": "Source - cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"continuous-load-source\", pod=~\"source-.*\", container=\"podinfo\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU Total"
    },
    {
     "expr": "irate(container_cpu_user_seconds_total{namespace=\"continuous-load-source\", pod=~\"source-.*\", container=\"podinfo\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU User"
    },
    {
     "expr": "irate(container_cpu_system_seconds_total{namespace=\"continuous-load-source\", pod=~\"source-.*\", container=\"podinfo\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU System"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}",
     "legendFormat": "{{ pod }} - {{ container }} CPU Request"
    }
   ]
  },
  {
   "title": "Istio Proxy (Inbound) - RPS by Workload, Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(source_workload_namespace, source_workload, response_code) (rate(istio_requests_total{\n    reporter=\"destination\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[$__rate_interval])) > 0",
     "legendFormat": "Workload {{source_workload_namespace}}/{{source_workload }} Response {{ response_code }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Inbound) - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{\n    reporter=\"destination\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\", response_code=\"200\"\n}[$__rate_interval])) /sum (rate(istio_requests_total{\n    reporter=\"destination\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[$__rate_interval])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Inbound) - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"destination\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"destination\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"destination\", destination_workload=\"source-podinfo\", destination_workload_namespace=\"continuous-load-source\"\n}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  {
   "title": "App - RPS by Path, Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_duration_seconds_count{\n    namespace=\"continuous-load-source\",\n}[$__rate_interval])) > 0",
     "legendFormat": "Request {{ path }} - Method {{ method }} Response  {{ status }}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"continuous-load-source\"}[$__rate_interval]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "App - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (path, method)(rate(http_request_duration_seconds_count{status=\"200\", namespace=\"continuous-load-source\"}[2m]))/sum by (path, method)(rate(http_request_duration_seconds_count{namespace=\"continuous-load-source\"}[2m])) * 100",
     "legendFormat": "Path: {{path}}, Method: {{ method }}"
    }
   ]
  },
  {
   "title": "App - Latency p90",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load-source\"}[2m])) by (le, path, method, status))",
     "legendFormat": "Path: {{path}} Method: {{method}} Status: {{status}}"
    }
   ]
  },
  {
   "title": "App - Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load-source\"}[2m])) by (le, path, method, status))",
     "legendFormat": "Path: {{path}} Method: {{method}} Status: {{status}}"
    }
   ]
  },
  {
   "title": "App - Latency p99.9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load-source\"}[2m])) by (le, path, method, status))",
     "legendFormat": "Path: {{path}} Method: {{method}} Status: {{status}}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - RPS by Workload, Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(destination_workload_namespace, destination_workload, response_code) (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"source-podinfo\", source_workload_namespace=\"continuous-load-source\"\n}[$__rate_interval])) > 0",
     "legendFormat": "Workload {{destination_workload_namespace}}/{{destination_workload }} Response {{ response_code }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{\n     reporter=\"source\", source_workload=\"source-podinfo\", source_workload_namespace=\"continuous-load-source\", response_code=\"200\"\n}[$__rate_interval])) /sum (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"source-podinfo\", source_workload_namespace=\"continuous-load-source\"\n}[$__rate_interval])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(istio_request_duration_milliseconds_bucket{\n     reporter=\"source\", source_workload=\"source-podinfo\", source_workload_namespace=\"continuous-load-source\"\n}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(istio_request_duration_milliseconds_bucket{\n     reporter=\"source\", source_workload=\"source-podinfo\", source_workload_namespace=\"continuous-load-source\"\n}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(istio_request_duration_milliseconds_bucket{\n     reporter=\"source\", source_workload=\"source-podinfo\", source_workload_namespace=\"continuous-load-source\"\n}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  { "title": "Target Podinfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Target - memory  RSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"continuous-load-target\", pod=~\"target-.*\", container=\"podinfo\"}",
     "legendFormat": "{{ pod }} - {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"continuous-load-target\", pod=~\"target-.*\", container=\"podinfo\"}",
     "legendFormat": "{{ pod }} - {{ container }} limit"
    }
   ]
  },
  {
   "title": "Target - cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"continuous-load-target\", pod=~\"target-.*\", container=\"podinfo\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU Total"
    },
    {
     "expr": "irate(container_cpu_user_seconds_total{namespace=\"continuous-load-target\", pod=~\"target-.*\", container=\"podinfo\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU User"
    },
    {
     "expr": "irate(container_cpu_system_seconds_total{namespace=\"continuous-load-target\", pod=~\"target-.*\", container=\"podinfo\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }} CPU System"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$ingress\", pod=~\"ingress-.*\", container=\"controller\"}",
     "legendFormat": "{{ pod }} - {{ container }} CPU Request"
    }
   ]
  },
  {
   "title": "Istio Proxy (Inbound) - RPS by Workload, Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(source_workload_namespace, source_workload, response_code) (rate(istio_requests_total{\n    reporter=\"destination\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[$__rate_interval])) > 0",
     "legendFormat": "Workload {{source_workload_namespace}}/{{source_workload }} Response {{ response_code }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Inbound) - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{\n    reporter=\"destination\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\", response_code=\"200\"\n}[$__rate_interval])) /sum (rate(istio_requests_total{\n    reporter=\"destination\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[$__rate_interval])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Inbound) - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"destination\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"destination\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(istio_request_duration_milliseconds_bucket{\n    reporter=\"destination\", destination_workload=\"target-podinfo\", destination_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  {
   "title": "App - RPS by Path, Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_duration_seconds_count{\n    namespace=\"continuous-load-target\",\n}[$__rate_interval])) > 0",
     "legendFormat": "Request {{ path }} - Method {{ method }} Response  {{ status }}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"continuous-load-target\"}[$__rate_interval]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "App - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (path, method)(rate(http_request_duration_seconds_count{status=\"200\", namespace=\"continuous-load-target\"}[2m]))/sum by (path, method)(rate(http_request_duration_seconds_count{namespace=\"continuous-load-target\"}[2m])) * 100",
     "legendFormat": "Path: {{path}}, Method: {{ method }}"
    }
   ]
  },
  {
   "title": "App - Latency p90",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load-target\"}[2m])) by (le, path, method, status))",
     "legendFormat": "Path: {{path}} Method: {{method}} Status: {{status}}"
    }
   ]
  },
  {
   "title": "App - Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load-target\"}[2m])) by (le, path, method, status))",
     "legendFormat": "Path: {{path}} Method: {{method}} Status: {{status}}"
    }
   ]
  },
  {
   "title": "App - Latency p99.9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(http_request_duration_seconds_bucket{namespace=\"continuous-load-target\"}[2m])) by (le, path, method, status))",
     "legendFormat": "Path: {{path}} Method: {{method}} Status: {{status}}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - RPS by Workload, Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(destination_workload_namespace, destination_workload, response_code) (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"target-podinfo\", source_workload_namespace=\"continuous-load-target\"\n}[$__rate_interval])) > 0",
     "legendFormat": "Workload {{destination_workload_namespace}}/{{destination_workload }} Response {{ response_code }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Success Rate (200 responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{\n     reporter=\"source\", source_workload=\"target-podinfo\", source_workload_namespace=\"continuous-load-target\", response_code=\"200\"\n}[$__rate_interval])) /sum (rate(istio_requests_total{\n    reporter=\"source\", source_workload=\"target-podinfo\", source_workload_namespace=\"continuous-load-target\"\n}[$__rate_interval])) * 100",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Istio Proxy (Outbound) - Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, \nsum(rate(istio_request_duration_milliseconds_bucket{\n     reporter=\"source\", source_workload=\"target-podinfo\", source_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(istio_request_duration_milliseconds_bucket{\n     reporter=\"source\", source_workload=\"target-podinfo\", source_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, \nsum(rate(istio_request_duration_milliseconds_bucket{\n     reporter=\"source\", source_workload=\"target-podinfo\", source_workload_namespace=\"continuous-load-target\"\n}[2m]))by (le))",
     "legendFormat": "P99.9"
    }
   ]
  }
 ]
}