name: bump-version
description: Bump the version of the charts

inputs:
  github-token:
    description: The GitHub Token to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        prefix: continuous-load-
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"

    - name: get previous version from tag
      id: previousversion
      shell: bash
      run: |
        echo "::set-output name=version::$(echo ${{ steps.previoustag.outputs.tag }} | cut -d'-' -f 3)"

    - name: Get next minor version
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previousversion.outputs.version }}

    - name: Set versions in Charts
      shell: bash
      run: |
        find . -type f -name 'Chart.yaml' -maxdepth 3 -exec sed -i -e 's|^version:.*|version: ${{ steps.semvers.outputs.minor }}|' {} \;
