apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
name: monitoring
description: A Helm chart to run the monitoring stack for continuous load

dependencies:
- name: prometheus
  version: "1.0.0"
  repository: "file://charts/prometheus"
- name: grafana
  version: "1.0.0"
  repository: "file://charts/grafana"
