{{- if eq .Values.global.promOperator "coreos" -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - {{.Release.Namespace}}
    - kube-system
  selector:
    matchExpressions:
    - {key: app.kubernetes.io/name, operator: Exists}
  endpoints:
  - port: http
    interval: 15s
  - port: https
    interval: 15s 
  - port: https-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics/cadvisor
    interval: 15s
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
{{- end -}}
{{- if eq .Values.global.promOperator "googleapis" -}}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: servicemonitor
  labels:
    release: prometheus
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchExpressions:
    - {key: app.kubernetes.io/name, operator: Exists}
  endpoints:
  - port: http
    interval: 15s
  - port: https
    interval: 15s
{{- end -}}