---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-grafanadatasource
spec:
  datasource:
    access: proxy
    type: prometheus
    jsonData:
      timeInterval: 15s
      tlsSkipVerify: true
    name: Prometheus
    url: {{.Values.prometheusUrl}}
  instanceSelector:
    matchLabels:
      dashboards: grafana