---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6
data:
  load.js: |-
{{ .Files.Get "load.js" | indent 6 }}
{{ if .Values.prometheusStatsd.enable -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: statsd-config
  labels:
    app.kubernetes.io/name: statsd-exporter
    app.kubernetes.io/instance: statsd
    app.kubernetes.io/version: "0.20.0"
data:
  statsd.mappingConf: |-
    defaults:
      observer_type: histogram
      histogram_options:
        buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
    mappings:
    - match: "k6.*"
      name: "k6_${1}"
    - match: "k6.check.*.*.*"
      name: "k6_check"
      labels:
        http_name: "$1"
        check_name: "$2"
        outcome: "$3"
    # - match: "k6\\.([^$]*)"
    #   match_type: regex
    #   name: "k6_${1}"
{{- end}}