{{- if eq .Values.promOperator "coreos" -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: k6
    role: alert-rules
  name: prometheus-k6-rules
spec:
  groups:
  - name: ./generator.rules
    rules: 
    ## Latency rules
    - alert: Continuous_Load_Generator_p99TooHigh
      expr: sum by(namespace, pod, type)
            (rate(k6_http_req_duration_bucket{namespace="{{.Release.Namespace}}", le="0,025"}[1m])) / 
            sum by(namespace, pod, type) 
            (rate(k6_http_req_duration_count{namespace="{{.Release.Namespace}}"}[1m])) < 0.99 
      for: 1m
      labels:
        role: generator
        severity: minor
      annotations:
        description: |-
          Namespace: `{{`{{`}} $labels.namespace {{`}}`}}`
          Pod: `{{`{{`}} $labels.pod {{`}}`}}`
          Type: `{{`{{`}} $labels.type {{`}}`}}`
          Percentage of requests served is under 25ms: {{`{{`}} $value | humanize {{`}}`}}
        summary: The percentage of requests served within the p99 latency threshold is less than 99%.
    ## Traffic rules
    - alert: Continuous_Load_Generator_NftTrafficTooLow
      expr: sum by(namespace, type) (rate(k6_http_reqs{namespace="{{.Release.Namespace}}"}[1m])) < 10
      for: 3m
      labels:
        role: generator
        severity: minor
      annotations:
        description: |-
          Namespace: `{{`{{`}} $labels.namespace {{`}}`}}`
          Type: `{{`{{`}} $labels.type {{`}}`}}`
          TPS: `{{`{{`}} $value | printf "%.0f" {{`}}`}}`
          Expected >= 10 for 3m
        summary: Traffic is too low in the NFT test so it might not be running correctly.
    - alert: Continuous_Load_Generator_NftTrafficTooHigh
      expr: sum by(namespace, type) (rate(k6_http_reqs{namespace="{{.Release.Namespace}}"}[1m])) > 100
      for: 3m
      labels:
        role: generator
        severity: minor
      annotations:
        description: |-
          Namespace: `{{`{{`}} $labels.namespace {{`}}`}}`
          Type: `{{`{{`}} $labels.type {{`}}`}}`
          TPS: `{{`{{`}} $value | printf "%.0f" {{`}}`}}`
          Expected < 100 for 3m
        summary: Traffic is too high in the NFT test so it might not be running correctly.
    ## Error rules
    - alert: Continuous_Load_Generator_AppError
      expr: sum by(namespace, pod, status) (rate(k6_http_reqs{ status!="200", namespace="{{.Release.Namespace}}"}[1m])) > 0.01
      labels:
        role: generator 
        severity: minor
      annotations:
        description: |-
          Namespace: `{{`{{`}} $labels.namespace {{`}}`}}`
          Pod: `{{`{{`}} $labels.pod {{`}}`}}`
          StatusCode: `{{`{{`}} $labels.status {{`}}`}}`
          Errors: `{{`{{`}} $value {{`}}`}}`
          Expected: 0
        summary: Errors have been reported.
    ## Saturation rules
    - alert: Continuous_Load_Generator_CpuTooHigh
      expr: sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!="istio-proxy", namespace="{{.Release.Namespace}}", pod=~"k6.*"}[1m])) -
            sum by(namespace, pod, container) (kube_pod_container_resource_requests{container!="istio-proxy", namespace="{{.Release.Namespace}}", pod=~"k6.*", resource="cpu", unit="core"}) > 0
      labels:
        role: generator
        severity: minor
      annotations:
        description: |-
          Namespace: `{{`{{`}} $labels.namespace {{`}}`}}`
          Pod: `{{`{{`}} $labels.pod {{`}}`}}`
          Container: `{{`{{`}} $labels.container {{`}}`}}`
          Container is using more CPU than requested, cpu burst is: `{{`{{`}} $value {{`}}`}}` cpu core
          Please investigate
        summary: The container is using more cpu than expected.
    - alert: Continuous_Load_Generator_MemoryTooHigh
      expr: (sum by(namespace, pod, container) (container_memory_rss{ container!="istio-proxy", namespace="{{.Release.Namespace}}", pod=~"k6.*"}) /
            sum by(namespace, pod, container) (kube_pod_container_resource_requests{container!="istio-proxy", namespace="{{.Release.Namespace}}", pod=~"k6.*", resource="memory", unit="byte"})) * 100 > 90
      labels:
        role: generator
        severity: minor
      annotations:
        description: |-
          Namespace: `{{`{{`}} $labels.namespace {{`}}`}}`
          Pod: `{{`{{`}} $labels.pod {{`}}`}}`
          Container: `{{`{{`}} $labels.container {{`}}`}}`
          Memory usage percentage: `{{`{{`}} $value | humanize {{`}}`}}`
          Expected <= 90% for 1m
        summary: The container is using more memory than expected.
{{- end -}}