name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Bump Version
        uses: ./.github/actions/bump-version
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          
      - name: Add dependency chart repos
        run: |
          helm repo add podinfo https://stefanprodan.github.io/podinfo

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"